version: 2

jobs:
  build:
    working_directory: ~/pedantic
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run: pip install codecov
      - run: tox
      - run: codecov
